# Generated by Django 3.2.11 on 2022-03-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_trabajados', models.PositiveIntegerField(default=0)),
                ('month', models.PositiveIntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
