# Generated by Django 3.2.11 on 2022-03-02 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio_unidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='fecha')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
