# Generated by Django 3.2.11 on 2022-02-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20220119_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchases',
            options={'ordering': ('-fecha',)},
        ),
    ]
