# Generated by Django 3.2.11 on 2022-03-02 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=250, unique_for_date='fecha')),
                ('tipo', models.CharField(choices=[('pintado', 'Pintado'), ('en blanco', 'En blanco')], default='pintado', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
