# Generated by Django 3.2.11 on 2022-05-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sena',
            field=models.IntegerField(default=0),
        ),
    ]
